spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
  kafka:
    bootstrap-servers: kafka:9092

server:
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    # To report to Eureka when this service is up
    registerWithEureka: true
    # Eureka server URL
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka:8761/eureka/}
  instance:
    # To avoid using DNS
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

minio:
  bucket:
    name: photos
  access:
    key: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_SECRET_KEY}
  url: http://minio:9001
