spring:
  application:
    name: marketplace
  datasource:
    url: "${MARKETPLACE_DB_URL}"
    username: "${DB_USER:root}"
    password: "${DB_PASSWORD:root}"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

server:
  # To avoid colliding with other apps in port 8080
  port: 8083

# App metadata
info:
  app:
    name: Marketplace MS
    description: Marketplace microservice for turism project
    version: 0.0.1-SNAPSHOT
  company:
    name: Turismo
    contact:
      email: support@turismo.com
      phone: +1234567890
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}
