spring:
  application:
    name: services

server:
  # To avoid colliding with other apps in port 8080
  port: 8082

# App metadata
info:
  app:
    name: Services MS
    description: Services microservice for turism project
    version: 0.0.1-SNAPSHOT
  company:
    name: Turismo
    contact:
      email: support@turismo.com
      phone: +1234567890
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}
