spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://${USERS_DB_HOST:localhost}:${USERS_DB_PORT:5432}/${USERS_DB_NAME:users}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

server:
  # To avoid colliding with other apps in port 8080
  port: 8081

# App metadata
info:
  app:
    name: Users MS
    description: Users microservice for turism project
    version: 0.0.1-SNAPSHOT
  company:
    name: Turismo
    contact:
      email: support@turismo.com
      phone: +1234567890
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}
