spring:
  application:
    name: users
  datasource:
    url: "${USERS_DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

keycloak:
  admin:
    username: "${KEYCLOAK_ADMIN}"
    password: "${KEYCLOAK_ADMIN_PASSWORD}"

server:
  # To avoid colliding with other apps in port 8080
  port: 8081

# App metadata
info:
  app:
    name: Users MS
    description: Users microservice for turism project
    version: 0.0.1-SNAPSHOT
  company:
    name: Turismo
    contact:
      email: support@turismo.com
      phone: +1234567890
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}
